### ISSUE TITLE
About adding hr

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/generic.shared#3]
I would like to know why `hr` element is not present in `margin-bottom` area. 
Is it because of its height that break vertical rhythm (in this case `hr` can have it's own area like in inuit v5). Or is it because `hr` have too much visual decision ?

Thanks in advance ;)

**Comment by csswizardry** [comment]
Currently, yeah, it’s because its height would break the vertical rhythm. Do you think that matters so much?

I suppose it might make sense to include the `hr` so that it has some default styling, then override it later on if you need to…?

**Comment by florianbouvot** [comment]
Right now I manage `hr` in base layer of ITCSS, so it's not really a problem for me.

I agree with you (`hr` style is often repetitive) so it can make sens to include a small default styling, but on the other hand I don't want to "overload" the framework

**Comment by csshugs** [comment]
:+1: 

Some default `hr` styling is one thing I really miss yet.
A browser reset and `margin-bottom` would be great and would close this little gap.

**Comment by florianbouvot** [comment]
😉
